/* eslint-disable @typescript-eslint/no-unused-vars */
// Auto-generated by `payload migrate:create` — do not edit by hand.
import { sql } from '@payloadcms/db-postgres'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "menus" ADD COLUMN "site_badge" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_brand_name" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_brand_suffix" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_address" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_tagline" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_search_placeholder" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_visit_kicker" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_visit_text" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_footer_note" varchar;
  ALTER TABLE "menus" ADD COLUMN "site_footer_brand" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "menus" DROP COLUMN "site_badge";
  ALTER TABLE "menus" DROP COLUMN "site_brand_name";
  ALTER TABLE "menus" DROP COLUMN "site_brand_suffix";
  ALTER TABLE "menus" DROP COLUMN "site_address";
  ALTER TABLE "menus" DROP COLUMN "site_tagline";
  ALTER TABLE "menus" DROP COLUMN "site_search_placeholder";
  ALTER TABLE "menus" DROP COLUMN "site_visit_kicker";
  ALTER TABLE "menus" DROP COLUMN "site_visit_text";
  ALTER TABLE "menus" DROP COLUMN "site_footer_note";
  ALTER TABLE "menus" DROP COLUMN "site_footer_brand";`)
}
