/* eslint-disable @typescript-eslint/no-unused-vars */
// Auto-generated by `payload migrate:create` — do not edit by hand.
import { sql } from '@payloadcms/db-postgres'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "menus_categories_subcategories_items" ADD COLUMN "available" boolean DEFAULT true;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "menus_categories_subcategories_items" DROP COLUMN "available";`)
}
