/* eslint-disable @typescript-eslint/no-unused-vars */
// Auto-generated by `payload migrate:create` — do not edit by hand.
import { sql } from '@payloadcms/db-sqlite'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_badge\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_brand_name\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_brand_suffix\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_address\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_search_placeholder\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_visit_kicker\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_visit_text\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_footer_note\` text;`)
  await db.run(sql`ALTER TABLE \`menus\` ADD \`site_footer_brand\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_badge\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_brand_name\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_brand_suffix\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_address\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_tagline\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_search_placeholder\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_visit_kicker\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_visit_text\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_footer_note\`;`)
  await db.run(sql`ALTER TABLE \`menus\` DROP COLUMN \`site_footer_brand\`;`)
}
